version = 1

test_patterns = ["**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "vitest"
  ]